language: python


git:
  depth: 99999


matrix:
  include:
    # - python: 3.3
    # - python: 3.4
    # - python: 3.5
    # - python: 3.6
    - python: 3.4.1

env:
  - APP_CONFIG_NAME=test


#install:
# - pip install -r requirements.txt
# - pip install codecov
# - pip install pytest-cov


before_script:
 - "export PYTHONPATH=."

#script:
#  - flake8 middleware/ --ignore=F401,F403,F405
#  - python -m pytest --cov=./


#after_success:
#  - codecov


before_deploy:
- echo 'start deploying!'

# Note, we currently share a single .travis.yml file amongst all branches
# Travis will raise the warning below, for all branches other than the current branch that
# is being tested. This warning can be safely ignored.
# "Skipping a deployment with the azure_web_apps provider because this branch is not permitted"

deploy:
  - provider: azure_web_apps
    verbose: true
    skip_cleanup: true
    on: master
    slot: science-gateway-users-dev

after_deploy: echo 'done deploying!'
