environment:
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python34"
    - PYTHON: "C:\\Python34-x64"

install:
  # We need wheel installed to build wheels
  #- "%PYTHON%\\python.exe -m pip install wheel"
  - "%PYTHON%\\python.exe -m pip install -r requirements.txt"

build: off

test_script:
  - ps: mkdir -p instance
  - ps: touch instance/config.py
  - "%PYTHON%\\python.exe -m pytest"

notifications:
  - provider: Slack
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: true
    incoming_webhook:
      secure: k56hsY5K++kvpU/bhF5r2YmgwSeTdGJVY8qnT8z9qRug/zgo50Ev8lB9kN4FT3vNJQpfmkDBOOlXe6XURHzaJPeTtDKKciAsXQe48IVkFVw=
